// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	broadcaster "go-feedmaker/infrastructure/rest/broadcaster"

	mock "github.com/stretchr/testify/mock"
)

// Broadcaster is an autogenerated mock type for the Broadcaster type
type Broadcaster struct {
	mock.Mock
}

// Register provides a mock function with given fields: recipient
func (_m *Broadcaster) Register(recipient broadcaster.Recipient) {
	_m.Called(recipient)
}
