// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// CloseHook is an autogenerated mock type for the CloseHook type
type CloseHook struct {
	mock.Mock
}

// Execute provides a mock function with given fields:
func (_m *CloseHook) Execute() {
	_m.Called()
}
