// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	http "net/http"

	mock "github.com/stretchr/testify/mock"

	websocket "github.com/gorilla/websocket"
)

// Upgrader is an autogenerated mock type for the Upgrader type
type Upgrader struct {
	mock.Mock
}

// Upgrade provides a mock function with given fields: _a0, _a1, _a2
func (_m *Upgrader) Upgrade(_a0 http.ResponseWriter, _a1 *http.Request, _a2 http.Header) (*websocket.Conn, error) {
	ret := _m.Called(_a0, _a1, _a2)

	var r0 *websocket.Conn
	if rf, ok := ret.Get(0).(func(http.ResponseWriter, *http.Request, http.Header) *websocket.Conn); ok {
		r0 = rf(_a0, _a1, _a2)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*websocket.Conn)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(http.ResponseWriter, *http.Request, http.Header) error); ok {
		r1 = rf(_a0, _a1, _a2)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
