version: '3.7'

networks:
  feedmaker_v2:
    name: "feedmaker_v2"
    driver: "bridge"

services:
  feedmaker_v2_app:
    build: .
    container_name: "feedmaker_v2_app"
    restart: "unless-stopped"
    depends_on:
      - "feedmaker_v2_redis"
    networks:
      - "feedmaker_v2"
    ports:
      - "8008:8000"
    env_file:
      - ".env"
    environment:
      REDIS_HOST: "feedmaker_v2_redis"
    volumes:
      - "./infrastructure/config/config.yml:/app/infrastructure/config/config.yml"
      - "./queries:/app/queries"

  feedmaker_v2_redis:
    container_name: "feedmaker_v2_redis"
    image: "redis:6-alpine"
    restart: "unless-stopped"
    networks:
      - "feedmaker_v2"
    volumes:
      - "./.data/redis:/data"
