// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// DataFetcher is an autogenerated mock type for the DataFetcher type
type DataFetcher struct {
	mock.Mock
}

// FetchDataStream provides a mock function with given fields: ctx
func (_m *DataFetcher) FetchDataStream(ctx context.Context) (<-chan []string, error) {
	ret := _m.Called(ctx)

	var r0 <-chan []string
	if rf, ok := ret.Get(0).(func(context.Context) <-chan []string); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(<-chan []string)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
