// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// DataFetcher is an autogenerated mock type for the DataFetcher type
type DataFetcher struct {
	mock.Mock
}

// OnDataFetched provides a mock function with given fields: _a0
func (_m *DataFetcher) OnDataFetched(_a0 func()) {
	_m.Called(_a0)
}

// OnProgress provides a mock function with given fields: _a0
func (_m *DataFetcher) OnProgress(_a0 func(uint)) {
	_m.Called(_a0)
}

// StreamData provides a mock function with given fields: ctx
func (_m *DataFetcher) StreamData(ctx context.Context) error {
	ret := _m.Called(ctx)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
