// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	interactor "go-feedmaker/interactor"
	io "io"

	mock "github.com/stretchr/testify/mock"
)

// FeedFactory is an autogenerated mock type for the FeedFactory type
type FeedFactory struct {
	mock.Mock
}

// CreateDataFetcher provides a mock function with given fields: outStream
func (_m *FeedFactory) CreateDataFetcher(outStream chan<- []string) interactor.DataFetcher {
	ret := _m.Called(outStream)

	var r0 interactor.DataFetcher
	if rf, ok := ret.Get(0).(func(chan<- []string) interactor.DataFetcher); ok {
		r0 = rf(outStream)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(interactor.DataFetcher)
		}
	}

	return r0
}

// CreateFileFormatter provides a mock function with given fields: inStream, outStream
func (_m *FeedFactory) CreateFileFormatter(inStream <-chan []string, outStream chan<- io.ReadCloser) interactor.FileFormatter {
	ret := _m.Called(inStream, outStream)

	var r0 interactor.FileFormatter
	if rf, ok := ret.Get(0).(func(<-chan []string, chan<- io.ReadCloser) interactor.FileFormatter); ok {
		r0 = rf(inStream, outStream)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(interactor.FileFormatter)
		}
	}

	return r0
}

// CreateUploader provides a mock function with given fields: inStream
func (_m *FeedFactory) CreateUploader(inStream <-chan io.ReadCloser) interactor.Uploader {
	ret := _m.Called(inStream)

	var r0 interactor.Uploader
	if rf, ok := ret.Get(0).(func(<-chan io.ReadCloser) interactor.Uploader); ok {
		r0 = rf(inStream)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(interactor.Uploader)
		}
	}

	return r0
}
