// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	interactor "go-feedmaker/interactor"

	mock "github.com/stretchr/testify/mock"
)

// Presenter is an autogenerated mock type for the Presenter type
type Presenter struct {
	mock.Mock
}

// PresentErr provides a mock function with given fields: err
func (_m *Presenter) PresentErr(err error) error {
	ret := _m.Called(err)

	var r0 error
	if rf, ok := ret.Get(0).(func(error) error); ok {
		r0 = rf(err)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// PresentGenerationTypes provides a mock function with given fields: _a0
func (_m *Presenter) PresentGenerationTypes(_a0 []string) interface{} {
	ret := _m.Called(_a0)

	var r0 interface{}
	if rf, ok := ret.Get(0).(func([]string) interface{}); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(interface{})
		}
	}

	return r0
}

// PresentListGenerations provides a mock function with given fields: out
func (_m *Presenter) PresentListGenerations(out *interactor.ListGenerationsOut) interface{} {
	ret := _m.Called(out)

	var r0 interface{}
	if rf, ok := ret.Get(0).(func(*interactor.ListGenerationsOut) interface{}); ok {
		r0 = rf(out)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(interface{})
		}
	}

	return r0
}
