// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// Uploader is an autogenerated mock type for the Uploader type
type Uploader struct {
	mock.Mock
}

// OnUpload provides a mock function with given fields: _a0
func (_m *Uploader) OnUpload(_a0 func(uint)) {
	_m.Called(_a0)
}

// UploadFiles provides a mock function with given fields: ctx
func (_m *Uploader) UploadFiles(ctx context.Context) error {
	ret := _m.Called(ctx)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
