// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	context "context"
	io "io"

	mock "github.com/stretchr/testify/mock"
)

// FtpGateway is an autogenerated mock type for the FtpGateway type
type FtpGateway struct {
	mock.Mock
}

// Upload provides a mock function with given fields: ctx, path, r
func (_m *FtpGateway) Upload(ctx context.Context, path string, r io.Reader) error {
	ret := _m.Called(ctx, path, r)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, io.Reader) error); ok {
		r0 = rf(ctx, path, r)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
