// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	context "context"
	io "io"

	mock "github.com/stretchr/testify/mock"
)

// FtpGateway is an autogenerated mock type for the FtpGateway type
type FtpGateway struct {
	mock.Mock
}

// ChangeDir provides a mock function with given fields: path
func (_m *FtpGateway) ChangeDir(path string) error {
	ret := _m.Called(path)

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(path)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ChangeDirToParent provides a mock function with given fields:
func (_m *FtpGateway) ChangeDirToParent() error {
	ret := _m.Called()

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MakeDir provides a mock function with given fields: path
func (_m *FtpGateway) MakeDir(path string) error {
	ret := _m.Called(path)

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(path)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// RemoveDir provides a mock function with given fields: dir
func (_m *FtpGateway) RemoveDir(dir string) error {
	ret := _m.Called(dir)

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(dir)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Upload provides a mock function with given fields: ctx, path, r
func (_m *FtpGateway) Upload(ctx context.Context, path string, r io.Reader) error {
	ret := _m.Called(ctx, path, r)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, io.Reader) error); ok {
		r0 = rf(ctx, path, r)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
