// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// CmdFunc is an autogenerated mock type for the CmdFunc type
type CmdFunc struct {
	mock.Mock
}

// Execute provides a mock function with given fields: _a0
func (_m *CmdFunc) Execute(_a0 ...interface{}) {
	var _ca []interface{}
	_ca = append(_ca, _a0...)
	_m.Called(_ca...)
}
