// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	context "context"

	cron "github.com/robfig/cron/v3"
	mock "github.com/stretchr/testify/mock"
)

// Croner is an autogenerated mock type for the Croner type
type Croner struct {
	mock.Mock
}

// Remove provides a mock function with given fields: _a0
func (_m *Croner) Remove(_a0 cron.EntryID) {
	_m.Called(_a0)
}

// Schedule provides a mock function with given fields: _a0, _a1
func (_m *Croner) Schedule(_a0 cron.Schedule, _a1 cron.Job) cron.EntryID {
	ret := _m.Called(_a0, _a1)

	var r0 cron.EntryID
	if rf, ok := ret.Get(0).(func(cron.Schedule, cron.Job) cron.EntryID); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Get(0).(cron.EntryID)
	}

	return r0
}

// Start provides a mock function with given fields:
func (_m *Croner) Start() {
	_m.Called()
}

// Stop provides a mock function with given fields:
func (_m *Croner) Stop() context.Context {
	ret := _m.Called()

	var r0 context.Context
	if rf, ok := ret.Get(0).(func() context.Context); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(context.Context)
		}
	}

	return r0
}
