// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"

	time "time"
)

// Nexter is an autogenerated mock type for the Nexter type
type Nexter struct {
	mock.Mock
}

// Next provides a mock function with given fields: _a0
func (_m *Nexter) Next(_a0 time.Time) time.Time {
	ret := _m.Called(_a0)

	var r0 time.Time
	if rf, ok := ret.Get(0).(func(time.Time) time.Time); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Get(0).(time.Time)
	}

	return r0
}
