// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	scheduler "go-feedmaker/infrastructure/scheduler"

	mock "github.com/stretchr/testify/mock"
)

// RedisClient is an autogenerated mock type for the RedisClient type
type RedisClient struct {
	mock.Mock
}

// Connection provides a mock function with given fields:
func (_m *RedisClient) Connection() scheduler.Connection {
	ret := _m.Called()

	var r0 scheduler.Connection
	if rf, ok := ret.Get(0).(func() scheduler.Connection); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(scheduler.Connection)
		}
	}

	return r0
}
