// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	repository "go-feedmaker/adapter/repository"

	mock "github.com/stretchr/testify/mock"
)

// RedisClient is an autogenerated mock type for the RedisClient type
type RedisClient struct {
	mock.Mock
}

// Connection provides a mock function with given fields:
func (_m *RedisClient) Connection() repository.Connection {
	ret := _m.Called()

	var r0 repository.Connection
	if rf, ok := ret.Get(0).(func() repository.Connection); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(repository.Connection)
		}
	}

	return r0
}
