// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	scheduler "go-feedmaker/infrastructure/scheduler"

	mock "github.com/stretchr/testify/mock"

	task "go-feedmaker/infrastructure/scheduler/task"
)

// ScheduleSaver is an autogenerated mock type for the ScheduleSaver type
type ScheduleSaver struct {
	mock.Mock
}

// Delete provides a mock function with given fields: _a0
func (_m *ScheduleSaver) Delete(_a0 scheduler.TaskID) error {
	ret := _m.Called(_a0)

	var r0 error
	if rf, ok := ret.Get(0).(func(scheduler.TaskID) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Load provides a mock function with given fields: _a0
func (_m *ScheduleSaver) Load(_a0 scheduler.TaskID) (*task.Schedule, error) {
	ret := _m.Called(_a0)

	var r0 *task.Schedule
	if rf, ok := ret.Get(0).(func(scheduler.TaskID) *task.Schedule); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*task.Schedule)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(scheduler.TaskID) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Store provides a mock function with given fields: _a0, _a1
func (_m *ScheduleSaver) Store(_a0 scheduler.TaskID, _a1 *task.Schedule) error {
	ret := _m.Called(_a0, _a1)

	var r0 error
	if rf, ok := ret.Get(0).(func(scheduler.TaskID, *task.Schedule) error); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
