// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	scheduler "go-feedmaker/infrastructure/scheduler"

	mock "github.com/stretchr/testify/mock"
)

// ScheduleSaver is an autogenerated mock type for the ScheduleSaver type
type ScheduleSaver struct {
	mock.Mock
}

// Delete provides a mock function with given fields: _a0
func (_m *ScheduleSaver) Delete(_a0 scheduler.TaskID) error {
	ret := _m.Called(_a0)

	var r0 error
	if rf, ok := ret.Get(0).(func(scheduler.TaskID) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ListScheduledTaskIDs provides a mock function with given fields:
func (_m *ScheduleSaver) ListScheduledTaskIDs() ([]scheduler.TaskID, error) {
	ret := _m.Called()

	var r0 []scheduler.TaskID
	if rf, ok := ret.Get(0).(func() []scheduler.TaskID); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]scheduler.TaskID)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Load provides a mock function with given fields: _a0
func (_m *ScheduleSaver) Load(_a0 scheduler.TaskID) (*scheduler.Schedule, error) {
	ret := _m.Called(_a0)

	var r0 *scheduler.Schedule
	if rf, ok := ret.Get(0).(func(scheduler.TaskID) *scheduler.Schedule); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*scheduler.Schedule)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(scheduler.TaskID) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Store provides a mock function with given fields: _a0, _a1
func (_m *ScheduleSaver) Store(_a0 scheduler.TaskID, _a1 *scheduler.Schedule) error {
	ret := _m.Called(_a0, _a1)

	var r0 error
	if rf, ok := ret.Get(0).(func(scheduler.TaskID, *scheduler.Schedule) error); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
