// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// StartStopper is an autogenerated mock type for the StartStopper type
type StartStopper struct {
	mock.Mock
}

// Start provides a mock function with given fields:
func (_m *StartStopper) Start() {
	_m.Called()
}

// Stop provides a mock function with given fields:
func (_m *StartStopper) Stop() {
	_m.Called()
}
