// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	scheduler "go-feedmaker/infrastructure/scheduler"

	mock "github.com/stretchr/testify/mock"
)

// Task is an autogenerated mock type for the Task type
type Task struct {
	mock.Mock
}

// Cmd provides a mock function with given fields:
func (_m *Task) Cmd() scheduler.Runner {
	ret := _m.Called()

	var r0 scheduler.Runner
	if rf, ok := ret.Get(0).(func() scheduler.Runner); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(scheduler.Runner)
		}
	}

	return r0
}

// Schedule provides a mock function with given fields:
func (_m *Task) Schedule() scheduler.Nexter {
	ret := _m.Called()

	var r0 scheduler.Nexter
	if rf, ok := ret.Get(0).(func() scheduler.Nexter); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(scheduler.Nexter)
		}
	}

	return r0
}
