logger:
  level: debug
  json_output: false

redis:
  host: "${REDIS_HOST|localhost}"
  port: "${REDIS_PORT|6379}"
  conn_timeout: "1s"
  pool_size: 5

ftp:
  host: "${FTP_HOST|localhost}"
  port: "${FTP_PORT|21}"
  username: "${FTP_USERNAME}"
  password: "${FTP_PASSWORD}"
  conn_timeout: "1s"

feeds:
  criteo_de:
    database:
      driver: "mssql"
      dsn: "sqlserver://${WAREHOUSE_USERNAME|user}:${WAREHOUSE_PASSWORD|password}@warehouse.jo?database=Marketing"
    line_limit: 100
    size_limit: "1000000MB"
    count_query: "queries/criteo_de/count.sql"
    select_query: "queries/criteo_de/select.sql"